<?php

$labels['settingslist'] = 'Anwendungsspzifische Passworte';
$labels['settingstitle'] = 'Anwendungsspzifische Passworte';

$labels['popup_expire_soon'] = 'Einige Ihrer anwendungsspzifischen Passworte laufen bald ab.';
$labels['popup_format_save_error'] = 'Fehler beim Speichern des Passworts: Das Format entsprach nicht dem erforderlichen Muster.';
$labels['popup_generic_save_error'] = 'Fehler beim Speichern des Passworts';
$labels['popup_duplicate_save_error'] = 'Fehler beim Speichern des Passworts: Verwenden Sie Anwendungsnamen nur einmalig.';
$labels['popup_successful_deletion'] = 'Eintrag erfolgreich gelöscht';
$labels['missingapplicationname'] = 'Bitte geben Sie einen gültigen Anwendungsnamen ein.';

$labels['application'] = 'Anwendung';
$labels['creation_date'] = 'Erstellt am';
$labels['expiry_date']   = 'Läuft ab';
$labels['created'] = 'Erstellt';
$labels['remove'] = 'Löschen';

$labels['name_field'] = 'Name:';
$labels['create_password'] = 'Gerneriere Passwort';
$labels['new_application_description'] = 'Erstellen Sie ein Passwort pro Anwendung (e.g. "My_Android", "mutt_office", ...).';
$labels['only_valid_characters'] = 'Sie können nur die folgenden Zeichen verwenden:';

$labels['new_application_ready'] = 'Ihr neues Passwort ist einsatzbereit für:';
$labels['new_application_copy']  = 'Klicken Sie auf das Passwort, um es zu kopieren.';
$labels['new_application_once']  = 'Das Passwort wird nur einmalig angezeigt.';
