<?php

$labels['created'] = 'Created';
$labels['remove'] = 'Remove';

$labels['settingslist'] = 'Application Specific Passwords';
$labels['settingstitle'] = 'Application Specific Passwords';

$labels['application'] = 'Application';
// Used in step 1 when creating new password
$labels['new_application_step1_legend'] = 'Step 1 of 2: Generate new application-specific password';
$labels['new_application_step1_description'] = 'Enter a name to help you remember what application this is for, like  "Bob\'s Android", "Outlook - home computer", "Thunderbird" ... .';
$labels['name_field'] = 'Name:';
$labels['create_password'] = 'Generate passsword';

// Used in step 2 when creating new password
$labels['new_application_step2_legend'] = 'Step 2 of 2: Enter the generated application-specific password';
$labels['new_application_step2_description'] = 'You may now enter your new application-specific password into your application. Note that this password grants complete access to your email account. Click on the password to copy it. For security reasons, it will not be displayed again:';
