<?php

$labels['settingslist'] = 'Application Specific Passwords';
$labels['settingstitle'] = 'Application Specific Passwords';

$labels['popup_expire_soon'] = 'Some of your application passwords will expire soon.';
$labels['popup_format_save_error'] = 'Error while saving your password: The format did not match the required pattern.';
$labels['popup_generic_save_error'] = 'Error while saving your password';
$labels['popup_duplicate_save_error'] = 'Error while saving your password: Do not reuse application names';
$labels['popup_successful_deletion'] = 'Successfully deleted the entry';
$labels['missingapplicationname'] = 'Please enter a valid application name.';

$labels['application'] = 'Application';
$labels['creation_date'] = 'Created at';
$labels['expiry_date']   = 'Expires at';
$labels['created'] = 'Created';
$labels['remove'] = 'Remove';

$labels['name_field'] = 'Name:';
$labels['create_password'] = 'Generate password';
$labels['new_application_description'] = 'Create one password per application (e.g. "My_Android", "mutt_office", ...).';
$labels['only_delete_one_password'] = 'The goal is that if you lose a device, you only need to delete the password for that device.';
$labels['only_valid_characters'] = 'You can only use the following characters:';
// this will be used in the placeholder of the input field, eg. "only use a-zA-Z0-9"
$labels['only_use'] = 'only use';

$labels['new_application_ready']      = 'Your new password is ready for:';
$labels['new_application_copy']       = 'You can click on the username and password to copy them.';
$labels['new_application_once'] = 'This password is only shown once.';
$labels['please_use_username'] = 'Please use the following username and password for this application.';
$labels['new_username'] = 'Username';
$labels['new_password'] = 'Password';
