<?php

$labels['settingslist'] = 'Senha da aplicação';
$labels['settingstitle'] = 'Senha da aplicação';

$labels['popup_expire_soon'] = 'Algumas das suas senhas de aplicação vão expirar.';
$labels['popup_format_save_error'] = 'Erro ao salvar sua senha: O formato não está de acordo com os requisitos necessários.';
$labels['popup_generic_save_error'] = 'Erro ao salvar sua senha';
$labels['popup_duplicate_save_error'] = 'Erro ao salvar sua senha: Nomes de aplicação não podem ser repetidos';
$labels['popup_successful_deletion'] = 'Entrada deletada com sucesso';
$labels['missingapplicationname'] = 'Por favor informe um nome de aplicação válido.';

$labels['application'] = 'Aplicação';
$labels['creation_date'] = 'Criado em';
$labels['expiry_date']   = 'Expira em';
$labels['created'] = 'Criado';
$labels['remove'] = 'Removido';

$labels['name_field'] = 'Nome:';
$labels['create_password'] = 'Gerar senha';
$labels['new_application_description'] = 'Crie uma senha diferente por aplicação (ex. "My_Android", "mutt_office", ...).';
$labels['only_delete_one_password'] = 'A razão para isso é que se você perder um device, você precisará apenas deletar a senha daquele device específico.';
$labels['only_valid_characters'] = 'Você pode usar apenas os seguintes caracteres:';
// this will be used in the placeholder of the input field, eg. "only use a-zA-Z0-9"
$labels['only_use'] = 'Use apenas';

$labels['new_application_ready']      = 'Sua nova senha esta pronta para:';
$labels['new_application_copy']       = 'Clique na senha para copiá-la.';
$labels['new_application_once'] = 'Esta senha será mostrada apenas uma vez.';
